version: '3'
services:
  postgres_db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis_cache:
    image: "redis:latest"
    ports:
      - "6379:6379"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev-client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    container_name: 'node-server'
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev-server
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres_db
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    container_name: 'node-worker'
    restart: always
    build:
      context: ./worker
      dockerfile: Dockerfile.dev-worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
    ports:
      - "5001:5001"
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
volumes:
  - ./client:/app
  - ./server:/app
  - ./worker:/app
