version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev-client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules 
      - ./client:/app
  node-server:
    # container_name: name
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev-server
    ports:
      - "5001:5001"
    volumes:
      - /app/node_modules
      - ./server:/app
  worker-app:
    restart: always
    build:
      context: ./worker
      dockerfile: Dockerfile.dev-worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    ports:
      - "5002:5002"
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
volumes:
  - ./client:/app
  - ./server:/app
  - ./worker:/app