version: '3'
services:
  redis-server: 
    image: 'redis'
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  node-server:
    restart: always
    volumes:
      - ./data/node:/data
    build: .
    ports:
      - "5001:6001"